name: CI Model Titanic

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
      # checkout repo dulu
      - name: checkout
        uses: actions/checkout@v4

      # setup python, kelas nyuruh pake 3.12
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # install dependencynya
      - name: install dependency
        run: |
          pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      # mulai training modelnya pake mlflow
      - name: training model
        run: mlflow run ./MLProject -e main --env-manager local

      # simpan model.pkl hasil training ke repo biar gak ilang
      - name: simpan model ke repo
        run: |
          git config user.email "7463765+ardianyusuf@users.noreply.github.com"
          git config user.name "Ardian Yusuf"
          git add model.pkl
          git commit -m "update model hasil training [skip ci]" || echo "tidak ada perubahan"
          git push
